name: Insecure Test
on: [push]
jobs:
  audit:
    runs-on: ubuntu-latest
    name: Insecure audit.
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd insecure && npm audit
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]
    name: Mashup lint.
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd mashup && npm install && npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]
    name: Unit Testing
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd mashup && npm install && npm test
