name: Insecure Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v3
     - name: Install jq tool
       run: |
          git clone https://github.com/awslabs/git-secrets /opt/git-secrets
          cd /opt/git-secrets && sudo make install
  audit:
    runs-on: ubuntu-latest
    name: Insecure audit.
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd insecure && npm audit
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]
    name: Mashup lint.
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd mashup && npm install && npm run lint

  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]
    name: Unit Testing
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd unittesting && npm install && npm test

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]
    name: Combined Testing
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd combined && npm audit
      - run: cd combined && npm install && npm run lint
      - run: cd combined && npm install && npm test
      - run: git secrets --scan-history
      

